# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS deimos_core

COPY images/deimos/files /

# Base Image
FROM ghcr.io/void-linux/void-glibc-full:latest

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    xbps-install -y -S bash

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/install-bootc.sh

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/build.sh

### LINTING
## Verify final image and contents are correct.
RUN bootc container lint
