# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS deimos_core

COPY images/deimos/files /

# Base Image
FROM ghcr.io/void-linux/void-glibc-full:latest

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    xbps-install -y -S bash

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    rm /bin/sh && ln -s /bin/bash /bin/sh

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/setup/users.sh

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/setup/install-bootc.sh

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/setup/build.sh

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/final/build-initramfs.sh


RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/final/rootfs-rebuild.sh

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/final/workarounds.sh

RUN --mount=type=bind,from=deimos_core,source=/,target=/deimos_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /deimos_core/scripts/final/clean-up.sh


### LINTING
## Verify final image and contents are correct.
LABEL containers.bootc=1
RUN bootc container lint
